# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: mavenbuild 
  jobs:
  - job:    
    steps:  
    - task: Maven@3
      inputs:
       mavenPomFile: '$(system.defaultWorkingDirectory)/azure-devops/01-hello-world-rest-api/pom.xml'
       publishJUnitResults: true
       testResultsFiles: '**/surefire-reports/TEST-*.xml'
       javaHomeOption: 'JDKVersion'
       jdkVersionOption: '1.8'
       mavenVersionOption: 'Default'
       mavenOptions: '-Xmx3072m'
       mavenAuthenticateFeed: false
       effectivePomSkip: false
       sonarQubeRunAnalysis: false
- stage: publishartifact
  dependsOn: mavenbuild
  jobs:
  - job:         
    steps:
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(system.defaultWorkingDirectory)/azure-devops/01-hello-world-rest-api/'
        artifact: 'helloworld'
        publishLocation: 'pipeline'
         
- stage: createdockerimageandpush
  dependsOn: publishartifact
  jobs:
  - job: 
    steps:
     - task: DownloadPipelineArtifact@2
       inputs:
         buildType: 'current'
         artifactName: 'helloworld'
         targetPath: '$(system.defaultWorkingDirectory)/azure-devops/01-hello-world-rest-api/'
         
    

